name: 🔀 Sync mirror to Gitee

on:
  push:
    branches:
      - master
  create:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror action
        continue-on-error: true
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'https://github.com/alibaba/x-render.git'
          destination-repo: 'git@gitee.com:x-render/x-render.git'
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: zhusijia1998@gmail.com
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: x-render/x-render
          branch: master