name: 🔀 Sync mirror to Gitee

on:
  push:
    branches:
      - master
  create:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror action
        continue-on-error: true
        if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag')
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:alibaba/x-render.git'
          destination-repo: 'git@gitee.com:x-render/x-render.git'
